# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LoCalendar' do

end

target 'LoCalendarTests' do

end

target 'LoCalendarUITests' do

end

pod 'Firebase', '>= 2.5.1'

